### ISSUE TITLE
Check the status when sending a message

### ISSUE THREAD

**Issue by helto4real** [net-daemon/net-hassclient#36]
[18:37:12 WRN] Home assistant is unavailable, retrying in 40 seconds...
[18:37:57 ERR] Failed to connect to Home Assistant on ws://supervisor/core/websocket
[18:37:59 WRN] Home Assistant Core still unavailable, retrying in 40 seconds...
[18:38:39 ERR] Major failure in WriteMessagePumpWriteMessagePump, exit...
System.Net.WebSockets.WebSocketException (198524992): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at JoySoftware.HomeAssistant.Client.WebSocketMessagePipeline`1.WriteMessagePump()
[18:38:44 ERR] Failed to connect to Home Assistant on ws://supervisor/core/websocket
[18:38:46 WRN] Home Assistant Core still unavailable, retrying in 40 seconds...
[18:39:26 ERR] Failed to connect to Home Assistant on ws://supervisor/core/websocket
[18:39:33 WRN] Home Assistant Core still unavailable, retrying in 40 seconds...
[18:40:13 ERR] Failed to connect to Home Assistant on ws://supervisor/core/websock

**Comment by helto4real** [comment]
Fixed
